//AUTOGENERATED - DO NOT TOUCH!
public struct InputAction {
    public const int MoveX = 0;
    public const int MoveY = 1;
    public const int Jump = 2;
    public const int Fire = 3;
    public const int PowerPrev = 4;
    public const int PowerNext = 5;
    public const int MenuX = 6;
    public const int MenuY = 7;
    public const int MenuAccept = 8;
    public const int MenuEscape = 9;
    public const int _count = 10;
}
